### PR TITLE
Fix compiling and readme

### PR DESCRIPTION
**Pull request by urherenow**
This makes building more trouble-free, for all systems.

### CODE REVIEW

**Comment by urherenow** [comment]
shoot. You've already made changes that breaks what I just changed.

**Comment by badda71** [comment]
Thanks for the PR. Regarding the change in the Makefile, romfs is actually used now :-)
Regarding your README.md update, I cannot reproduce the issue. I just checked by installing a fresh download of devkitpro on windows, typed the tree commands and everything compiles fine.

**Comment by urherenow** [comment]
I closed the request because of the romfs changes though. And not everyone uses Windows to compile (in fact, MOST people who compile code use a Linux environment).

Your latest commits with the romfs stuff doesn’t even run for me. Instant crash. Are you actually trying to update/write to config files that are stored inside of the .3dsx, or are you storing them there, to create the config folder and extract the default ones, if not already present? Seems like an odd thing to do. Having files packed into the .3dsx that need to be written to, is even weirder. .3dsx files aren’t meant for that.

**Comment by WinterMute** [comment]
1. devkitPro is an organisation, not software. You don't install a fresh download of devkitPro - our windows installer installs a slightly modified msys2 then uses pacman from that to install the packages.
2. Out statistics show that windows users of our toolchains outnumber linux users by some 20:1 so most users aren't compiling on linux.
3. You really, really shouldn't be writing to files inside romfs in the 3dsx if that's what you're doing.

**Comment by badda71** [comment]
Hm actually, I wanted to pack the config files into the 3dsx so that there is only one file to distribute. These config files are used as fallback if there are no config files on the SD card. I adjusted the code not to try to write to these files when saving the config and rather use the SD card. Maybe I did not catch every piece of code that writes to these config files. In Citra, the build works - need to check with a real 3ds

**Comment by WinterMute** [comment]
Sorry, was editing the other comment when you replied.

Rather than saying "You need devkitpro w/ devkitARM" just say devkitARM. 

4. p7zip & pkg-config are host packages and cannot be installed by (dkp-)pacman on osx/linux. @urherenow is correct, these should be installed separately by the host package management tool (apt/dnf/yum or even pacman on arch). Might be better to just say "install p7zip and pkg-config with your system package manager'

5. I just checked our romfs implementation is read only so if writing does crash then it's a bug on our end & should be reported - probably better in devkitPro forums, not sure if that'll be devkitARM or libctru related without checking.

**Comment by badda71** [comment]
changed README.md
And I will take out the romfs support for now ...

**Pull request closed without merging**
